project/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path("cities/", include("weathers.urls")),
    path('', home, name="home"),

]

weathers/urls.py
from django.urls import path
from . import views

app_name = 'weathers'

urlpatterns = [
    path("", views.index, name="cities"),
    path('<int:pk>', views.detail, name = 'city'),
    path('add', views.add_city, name = 'city_add'),
    path('delete/<int:pk>/', views.delete_city, name = 'city_delete'),
    path('update/<int:pk>/', views.update_city, name = 'city_update'),
    path('weathers/', views.weathers_view, name = 'weathers'),
]

weathers/models.py
from django.db import models


class BaseModel(models.Model):
    objects = models.Manager()
    class Meta:
        abstract = True

COUNTRY_CHOICES = {
    "Lietuva": "Lietuva",
    "Latvija": "Latvija",
    "Estija": "Estija",
    "JAV": "JAV",
    "Australija": "Australija",
    "Ispanija": "Ispanija",
    "Grenlandija": "Grenlandija",
    "Turkija": "Turkija",
}


class City(BaseModel):
    name = models.CharField(max_length=50, default='', blank=True, unique=True)
    country = models.CharField(default='Lietuva', max_length=100, choices=COUNTRY_CHOICES)
    coordination_x = models.FloatField(default=0)
    coordination_y = models.FloatField(default=0)
    temperature = models.FloatField(null=True, blank=True)

    def __str__(self):
        return f'({self.name} in {self.country}, coordination: {self.coordination_x, self.coordination_y})'


class CityWeathers(BaseModel):
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    temperature = models.FloatField(default=0)
    wind = models.FloatField(default=0)
    humidity = models.FloatField(default=0)
    time_stamp = models.DateTimeField(auto_now=True)

weathers/forms.py
from django import forms
from .models import City
from django.forms import ModelForm, Textarea

class NameForm(forms.Form):
    city = forms.CharField(label='city', max_length=50, min_length=3)
    country = forms.CharField(label='country', max_length=50, min_length=3)
    coordination_x = forms.FloatField(label='coordination_x', max_value=120, min_value=0)
    coordination_y = forms.FloatField(label='coordination_y', max_value=120, min_value=0)

class CityForm(ModelForm):
    class Meta:
        model = City
        fields = ('name', 'country', 'coordination_x', 'coordination_y')

project/views.py
from django.shortcuts import render

from weathers.helper_function.weathers import get_temperature, get_wind, get_humidity
from weathers.models import City

def home(request):
    try:
        favorite_city = City.objects.get(name='Vilnius')
        temperature = get_temperature(favorite_city.coordination_x, favorite_city.coordination_y)
        wind = get_wind(favorite_city.coordination_x, favorite_city.coordination_y)
        humidity = get_humidity(favorite_city.coordination_x, favorite_city.coordination_y)

    except City.DoesNotExist:
        favorite_city = None
        temperature = None
        wind = None
        humidity = None

    context = {
        'favorite_city': favorite_city,
        'temperature': temperature,
        'wind': wind,
        'humidity': humidity,
    }
    return render(request=request, template_name="home.html", context=context)

weathers/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .helper_function.weathers import get_temperature, get_wind, get_humidity, get_hourly_forecast
from .models import City, CityWeathers
from django.urls import reverse
from .forms import CityForm


def index(request):
    cities = City.objects.all()
    for city in cities:
        city.temperature = get_temperature(city.coordination_x, city.coordination_y)
    context = {'cities':cities}
    return render(request=request, template_name= "weathers/cities.html", context= context)

def detail(request, pk):
    city = None
    try:
        city = City.objects.get(id=pk)
    except City.DoesNotExist:
        pass

    current_temperature = get_temperature(city.coordination_x, city.coordination_y)
    current_wind = get_wind(city.coordination_x, city.coordination_y)
    current_humidity = get_humidity(city.coordination_x, city.coordination_y)
    city_hourly_forecast = get_hourly_forecast(city.coordination_x, city.coordination_y)

    context = {
        'city':city,
        'cities':City.objects.all(),
        'temperature': current_temperature,
        'wind': current_wind,
        'humidity': current_humidity,
        'forecast': city_hourly_forecast,
    }

    city_weathers = CityWeathers.objects.create(city=city, temperature=current_temperature,
                                                wind = current_wind, humidity = current_humidity)
    city_weathers.save()

    return render(request=request, template_name= "weathers/city.html", context= context)


def weathers_view(request):
    city_weathers = CityWeathers.objects.all().order_by('-time_stamp')
    context = {'city_weathers':city_weathers}
    return render(request = request, template_name = 'weathers/weathers.html', context = context)


def delete_city(request, pk):
    city = City.objects.get(id=pk)
    if request.method == 'POST':
        city.delete()
        return HttpResponseRedirect(reverse('weathers:cities'))
    context = {'city':city}
    return render(request=request, template_name='weathers/city_confirm_delete.html', context=context)

def update_city(request, pk):
    city = City.objects.get(id = pk)
    if request.method == 'POST':
        form = CityForm(request.POST, instance = city)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('weathers:cities'))
    else:
        form = CityForm(instance = city)
    context = {'form': form}
    return render(request=request, template_name='weathers/city_add_1.html', context=context)


def add_city(request):
    if request.method == 'POST':
        form = CityForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('weathers:cities'))

    else:
        form = CityForm()
    context = {'form':form}
    return render(request=request, template_name='weathers/city_add_1.html', context=context)

templates/home.html
{% extends 'main.html' %}

{% block content %}

    {% if favorite_city %}
        <div class="cityDecor">
            <h1>Weather Information for {{ favorite_city.name }}</h1>
            <h1>{{ favorite_city.country }}</h1>
            <p>Coordinates: {{ favorite_city.coordination_x }}, {{ favorite_city.coordination_y }} </p>
            <h2>Temperature: {{ temperature }} °C </h2>
            <h2>Wind: {{ wind }} KM/H </h2>
            <h2>Humidity: {{ humidity }} % </h2>
        </div>


    {% else %}
        <p>No favorite city is set. Please update the default city.</p>
    {% endif %}
 

{% endblock %}

templates/main.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Weather_app</title>    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&family=Rowdies:wght@300;400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/utilities_screen.css' %}">
    <link rel="stylesheet" href="{% static 'css/button.css' %}">
  </head>
  <body>

    <header>
      {% include 'navbar.html' %}
    </header>

    <main class="mainDecor">
      {% block content %}


      {% endblock %}
    </main>

    <footer class="footerDecor">
      <p>&copy UAB The Weather app. 2025</p>
    </footer>

    <script src="{% static 'js/main.js' %}"></script>    
  </body>
</html>

templates/navbar.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <header>
    <nav class="flex">
          <div>
            <a href="{% url 'home' %}"><img class="weatherLogo" src="{% static 'img/weatherLogo.png' %}" alt="logo" ></a>                 
            <a class="appName" href="{% url 'home' %}">Weathers App</a>
          </div>        
          <input id="menu__toggle" type="checkbox" />
          <label class="menu__btn" for="menu__toggle">
              <span></span>
          </label>
          <ul class="menu__box">
            <li>
              <a class="menu__item" href="{% url 'home' %}">Home</a>
            </li>
            <li>
              <a class="menu__item" href="{% url 'weathers:cities' %}">Cities</a>
            </li>
            <li>
              <a class="menu__item" href="{% url 'weathers:weathers' %}">Weathers History</a>
            </li>
          </ul>                    
    </nav>
  </header>
</body>
</html>

weathers/templates/weathers/cities.html
{% extends 'main.html' %}

{% block content %}

    {% if cities %}
        <ul class="citiesDecor">
        {% for city in cities %}
            <li><a class="cityDecor citiesDecor cityLinkDecor" href = "{% url 'weathers:city' city.id %}">
                {{ city.name }} {{ city.country}} {{ city.temperature }} °C</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No cities are available.</p>
    {% endif %}
<a href = "{% url 'weathers:city_add' %}">
    <button type="button" class="btn">Add city</button>
</a>

{% endblock %}

weathers/templates/weathers/city.html
{% extends 'main.html' %}

{% block content %}

    {% if city %}
    <div class="cityDecor">
        <h1>{{ city.name }}, {{ city.country }}</h1>
        <p>Coordinates: {{ city.coordination_x }}, {{ city.coordination_y }} </p>
        <h3>Temperature: {{ temperature }} °C </h3>
        <h3>Wind: {{ wind }} KM/H </h3>
        <h3>Humidity: {{ humidity }} % </h3>
        <h3>Next 8 Hours Forecast:</h3>
        <table class="tableDecor">
            <thead>
                <tr>
                    <th>Time</th>
                    <th>Temperature (°C)</th>
                    <th>Wind (KM/H)</th>
                    <th>Humidity (%)</th>
                </tr>
            </thead>
            <tbody>
                {% for entry in forecast %}
                <tr>
                    <td>{{ entry.time }}</td>
                    <td>{{ entry.temperature }}</td>
                    <td>{{ entry.wind_speed }}</td>
                    <td>{{ entry.humidity }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
        <a href="{% url 'weathers:city_delete' city.id %}">
            <button type="button" class="deleteBtn">Delete city</button>
        </a>
        <a href="{% url 'weathers:city_update' city.id %}">
            <button type="button" class="btn">Update city</button>
        </a>
    {% else %}
        <ul>            
            {% for city in cities %}
                <li><a href = "{% url 'weathers:city' city.id %}">{{ city.name }} {{ city.country}} </a></li>
            {% endfor %}
        </ul>
    {% endif %}

{% endblock %}

weathers/templates/weathers/city_add.html
{% extends 'main.html' %}

{% block content %}
        <p>Please enter City data: </p>

        <form method="post">
                {% csrf_token %}
                <label for="city"> city: </label></br>
                <input id="city" type="text" name="city"></br>
                <label for="country"> country: </label></br>
                <input id="country" type="text" name="country"></br>
                <label for="coordination_x"> coordination_x: </label></br>
                <input id="coordination_x" type="number" name="coordination_x"></br>
                <label for="coordination_y"> coordination_y: </label></br>
                <input id="coordination_y" type="number" name="coordination_y"></br></br>
                <input type="submit" value="Add">
        </form>


{% endblock %}

weathers/templates/weathers/city_add_1.html
{% extends 'main.html' %}

{% block content %}

        <form class="formDecor" method="post">
                {% csrf_token %}
                {{ form }}
                <button class="btn" type="submit" value="Save">Save</button>
        </form>

{% endblock %}

weathers/templates/weathers/city_confirm_delete.html
{% extends 'main.html' %}

{% block content %}

<body>
    <h1>Are you sure to delete '{{ city.name }}'?</h1>

    <form method="POST">
        {% csrf_token %}
        <button type="submit" class="deleteBtn">Yes, delete</button>
    </form></br>
    <a href="{% url 'weathers:cities' %}">
        <button type="button" class="btn">Cancel</button>
    </a>
</body>

{% endblock %}

weathers/templates/weathers/weathers.html
{% extends 'main.html' %}

{% block content %}

     <table class="tableDecor">
  <thead>
    <tr>
      <th>Country</th>
      <th>City name</th>
      <th>Coordinates (x)</th>
      <th>Coordinates (y)</th>
      <th>Temperature</th>
      <th>Wind</th>
      <th>Humidity</th>
      <th>Checking Time</th>
    </tr>
  </thead>
  <tbody>
    {% for city in city_weathers %}
    <tr>
      <td>{{ city.city.country }}</td>
      <td>{{ city.city.name }}</td>
      <td>{{ city.city.coordination_x }}</td>
      <td>{{ city.city.coordination_y }}</td>
      <td>{{ city.temperature }}</td>
      <td>{{ city.wind }}</td>
      <td>{{ city.humidity }}</td>
      <td>{{ city.time_stamp }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}